### ISSUE TITLE
sudo not found during "docker-compose run compile"

### ISSUE THREAD

**Issue by nbatsukh** [appPlant/goo#19]
Here is a part of the console output

3 gems installed
ssh-keygen: generating new host keys: RSA DSA ECDSA ED25519 
install.sh: line 66: sudo: not found
 ---> 6c273daad4c1
Removing intermediate container 656efbca896b
Step 8 : RUN gem install rake os test-unit --no-ri --no-rdoc
 ---> Running in 7e7e95dca8b0
Successfully installed rake-12.0.0
Successfully installed os-0.9.6

**Comment by nbatsukh** [comment]
Apparently in the image, there is no sudo package installed.
```sh
docker-compose run shell 
```
gives me the same error.

Besides, the docker daemon runs as root according to the docs, so sudo is not necessary IMHO.
The line of code in question is:

```sh
sudo /usr/bin/sshd
```

I suggest to changing it to just /usr/bin/sshd or sshd for that matter.

**Comment by MrBlaTi** [comment]
can't reproduce, travis-ci doesn't reproduce the error as well.

**Comment by nbatsukh** [comment]
install.sh is no more. So I am closing this issue.
