### ISSUE TITLE
Use new ski format

### ISSUE THREAD

**Issue by katzer** [appPlant/goo#36]
With fifa v1.4.1 the ski format comes with an additional entry (valid bit).

    $ ff --no-color -f=ski
    1|package-1|server|App Package 1|user@hostname.de
    0|package-2|server|App Package 2|missing user

See https://github.com/appPlant/ff/pull/3 for more info.

**Comment by MrBlaTi** [comment]
fixed by #37

**Comment by nbatsukh** [comment]
Closed apparently.
